# Generated by Django 4.2.3 on 2023-09-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactDataType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("validation_regex", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100)),
                ("nickname_or_phone", models.CharField(max_length=100)),
                (
                    "contact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contact_manager.contact"),
                ),
                (
                    "contact_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contact_manager.contactdatatype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(related_name="contacts", to="contact_manager.group"),
        ),
    ]
